--CREATE TABLE usuarios (id int NOT NULL AUTO_INCREMENT,
--	nome VARCHAR (250) NOT NULL,
--	email VARCHAR (250) NOT NULL,
--	SENHA VARCHAR (250) NOT NULL,
--	ultimoLoin timestamp NOT NULL,
--	CONSTRAINT pk_usuarios_id PRIMARY KEY (id));